<?php
// Position represents one row from the MySQL position table.
class Position {
    // Stores the primary key generated by MySQL.
    private $id;
    // Stores the latitude value received from Android GPS.
    private $latitude;
    // Stores the longitude value received from Android GPS.
    private $longitude;
    // Stores the datetime when Android collected the position.
    private $date;
    // Stores the Android device identifier in the lab imei column.
    private $imei;

    // Builds a Position object from table field values.
    public function __construct($id, $latitude, $longitude, $date, $imei) {
        // Assigns the database id to this object.
        $this->id = $id;
        // Assigns the latitude to this object.
        $this->latitude = $latitude;
        // Assigns the longitude to this object.
        $this->longitude = $longitude;
        // Assigns the datetime to this object.
        $this->date = $date;
        // Assigns the device identifier to this object.
        $this->imei = $imei;
    }

    // Returns the position id.
    public function getId() {
        // Sends the private id value back to the caller.
        return $this->id;
    }

    // Updates the position id.
    public function setId($id) {
        // Stores the new id value.
        $this->id = $id;
    }

    // Returns the latitude.
    public function getLatitude() {
        // Sends the private latitude value back to the caller.
        return $this->latitude;
    }

    // Updates the latitude.
    public function setLatitude($latitude) {
        // Stores the new latitude value.
        $this->latitude = $latitude;
    }

    // Returns the longitude.
    public function getLongitude() {
        // Sends the private longitude value back to the caller.
        return $this->longitude;
    }

    // Updates the longitude.
    public function setLongitude($longitude) {
        // Stores the new longitude value.
        $this->longitude = $longitude;
    }

    // Returns the datetime.
    public function getDate() {
        // Sends the private date value back to the caller.
        return $this->date;
    }

    // Updates the datetime.
    public function setDate($date) {
        // Stores the new datetime value.
        $this->date = $date;
    }

    // Returns the device identifier.
    public function getImei() {
        // Sends the private imei value back to the caller.
        return $this->imei;
    }

    // Updates the device identifier.
    public function setImei($imei) {
        // Stores the new imei value.
        $this->imei = $imei;
    }
}
?>
